Repository Prateek9876/NagarVikas, pull requests merged in 2025-07, with the labels that each got.

#114 Fixed drawer alignment
  lib/screen/issue_selection.dart
Labels: Beginner, SSOC'25 S4

#125 added .editorconfig file
  .editorconfig
Labels: Intermediate, SSOC'25 S4

#126 🔔 Added in-app notification system for new complaints (#121)
  android/gradle.properties
  lib/screen/admin_dashboard.dart
  lib/screen/issue_selection.dart
  lib/widgets/exit_confirmation.dart
  pubspec.lock
  pubspec.yaml
Labels: Advanced, SSOC'25 S4

#151 notification updated in loginpage
  lib/screen/login_page.dart
Labels: Intermediate, SSoC25

#154 Improve UI of Admin Dashboard Appbar (Again Submit)
  android/app/build.gradle
  android/build.gradle
  android/gradle.properties
  lib/screen/admin_dashboard.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC'25, level 2

#162 Refactor and enhance various screens and services
  lib/components/shared_issue_form.dart
  lib/main.dart
  lib/screen/about.dart
  lib/screen/admin_dashboard.dart
  lib/screen/analytics_dashboard.dart
  lib/screen/complaint_detail_page.dart
  lib/screen/discussion.dart
  lib/screen/facing_issues.dart
  lib/screen/feedback.dart
  lib/screen/fun_game_screen.dart
  lib/screen/issue_selection.dart
  lib/screen/login_page.dart
  lib/screen/logo.dart
  lib/screen/my_complaints.dart
  lib/screen/profile_screen.dart
  lib/screen/referearn.dart
  lib/screen/register_screen.dart
  lib/service/connectivity_service.dart
  lib/service/notification_service.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/exit_confirmation.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  web_entrypoint.dart
Labels: GSSOC'25, level 2
