Repository Prateek9876/NagarVikas, pull requests merged in 2025-08, with the labels that each got.

#201 Improved UI of Admin Dashboard #137 Level 2
  lib/screen/admin_dashboard.dart
  lib/screen/favourites.dart
Labels: GSSOC'25, level 2

#224 Updated README.md
  README.md
Labels: GSSOC'25, level 2

#216 Changed the Rejected Option to Pending in Admin Dashboard Analytics #211 Level 3
  lib/screen/analytics_dashboard.dart
  lib/screen/complaint_details_page.dart
  lib/widgets/pie_chart_widget.dart
Labels: GSSOC'25, level 3

#219 Improved UI for the Discussion Forum
  lib/screen/discussion.dart
  pubspec.yaml
Labels: GSSOC'25, level 3

#234 Fixed validation errors showing before input on Sign Up page #227 Level 2
  lib/screen/register_screen.dart
Labels: GSSOC'25, level 2

#245 Redesigned Profile Page #243 Level 3
  lib/screen/profile_screen.dart
Labels: GSSOC'25, level 3

#242 Improved the feedback screen for users #235 Level 3
  lib/screen/feedback.dart
Labels: GSSOC'25, level 3

#254 Working Dark Mode option in Admin's Dashboard Screen
  lib/widgets/bar_chart_widget.dart
  lib/widgets/bottom_nav_bar.dart
  lib/widgets/chatbot_wrapper.dart
Labels: GSSOC'25, level 3

#268 Working Dark mode in Authentication pages like Login/Signup pages
  lib/service/local_status_storage.dart
  lib/widgets/bar_chart_widget.dart
  lib/widgets/pie_chart_widget.dart
Labels: GSSOC'25, level 3

#357 Improved the UI of Game Model with Current Theme #319 Level 3
  lib/model/game_model.dart
Labels: GSSOC'25, level 3

#337 Updated Terms & Conditions Acceptance Popup #262 Level 3
  lib/screen/issue_selection.dart
Labels: GSSOC'25, level 3

#370 Improved the UI of About NagarVikas Page with Current Theme #316 Level 3
  lib/screen/about.dart
Labels: GSSOC'25, level 3

#371 Improved the Discussion Forum UI #325
  lib/screen/discussion.dart
Labels: GSSOC'25, level 3

#372 Added a Help Center Page #331 Level 3
  lib/screen/help_center.dart
  lib/screen/profile_screen.dart
Labels: GSSOC'25, level 3

#377 Fixed discussion forum button issue
  lib/screen/issue_selection.dart
Labels: GSSOC'25, level 2

#379 Solved Bottom Nav Logout Issue in Admin #314
  lib/screen/admin_dashboard.dart
  lib/screen/analytics_dashboard.dart
Labels: GSSOC'25, level 2

#380 The Bottom Nav shows above the drawer.
  lib/screen/profile_screen.dart
  lib/service/local_status_storage.dart
  lib/widgets/bottom_nav_bar.dart
Labels: GSSOC'25, level 2

#383 Change the UI of the Pop Up Dialog Boxes #324 Level 3
  lib/screen/admin_dashboard.dart
Labels: GSSOC'25, level 3

#389 Added Phone Number Field in Complaint Page with Backend Integration #338 Level 3
  lib/screen/complaint_detail_page.dart
Labels: GSSOC'25, level 3

#390 Added Send Image in Discussion Page with Backend Integration #308 Level 3
  lib/screen/discussion.dart
  pubspec.yaml
Labels: GSSOC'25, level 3

#392 Added working filter in admin's dashboard
  lib/screen/admin_dashboard.dart
Labels: GSSOC'25, level 2

#391 Added emoji section and segregated dates
  lib/screen/discussion.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
Labels: GSSOC'25, level 3

#393 Fixed the blank screen problem on going back from the profile screen
  lib/screen/modern_app_drawer.dart
  lib/screen/profile_screen.dart
  lib/widgets/bottom_nav_bar.dart
Labels: GSSOC'25, level 2

#396 Allow editing your own message in Discussion Forum
  lib/screen/discussion.dart
Labels: GSSOC'25, level 2

#397 Added the Full Working Profile Page #293 Level 3
  lib/screen/profile_screen.dart
Labels: GSSOC'25, level 3

#401 Added Speech to Text functionlity in Discussion Forum
  lib/screen/discussion/discussion.dart
Labels: GSSOC'25, level 2

#404 Added delete functionality and reply to own messages functionality
  lib/screen/discussion/discussion.dart
  lib/screen/discussion/message_widgets.dart
Labels: GSSOC'25, level 1

#425 Added text attachment to image/videos in discussion forum and fixed scroll to bottom even if media is there.
  lib/screen/discussion/discussion.dart
Labels: GSSOC'25, level 2

#426 On long pressing any message in the discussion forum it automatically scrolls to the latest chat, so fix it. Fix unnecessary back button in Spell Records and Profile page.
  lib/screen/modern_app_drawer.dart
  lib/screen/my_complaints.dart
Labels: GSSOC'25, level 2

#428 Maximum character limit in message box and scrollable message box so that overflow does not occur. Also fix a reply overlapping issue.
  lib/screen/discussion/discussion.dart
Labels: GSSOC'25, level 2

#430 Add the contributors section in readme.md (updates after every week)
  .github/workflows/update-contributors.yml
  README.md
Labels: GSSOC'25, level 1

#431 Improved the Admin Drawer UI #285 Level 3
  lib/screen/admin_dashboard.dart
  lib/screen/admin_drawer.dart
Labels: GSSOC'25, level 3

#434 Added the Feature to Upvote and Downvote in Discussion Forum #361
  lib/screen/discussion/discussion.dart
  lib/screen/discussion/message_widgets.dart
Labels: GSSOC'25, level 2

#441 Solved Messages Take too Much Horizontal Space Issue #437
  lib/screen/discussion/message_widgets.dart
Labels: GSSOC'25, level 2

#442 Added the OTP Verification Method Via SMS #436 Level 3
  android/app/src/main/AndroidManifest.xml
  lib/screen/register_screen.dart
Labels: GSSOC'25, level 3

#443 Updated the Phone Number Edit Functionality with OTP Verification #435
  lib/screen/profile_screen.dart
Labels: GSSOC'25, level 1

#447 Working Report Issue
  lib/screen/profile_screen.dart
  lib/screen/report_issue_service.dart
Labels: GSSOC'25, level 3

#449 Made report in Discussion Forum from User's POV
  functions/index.js
  lib/screen/discussion/discussion.dart
  lib/screen/discussion/message_reporting_screen.dart
Labels: GSSOC'25, level 2

#455 Message Box no visible bug, Long press overflow issue (for admin) and Shimmers according to dark mode
  functions/index.js
  lib/screen/admin_dashboard.dart
  lib/screen/admin_drawer.dart
  lib/screen/discussion/discussion.dart
  lib/screen/discussion/message_reporting_screen.dart
  lib/screen/my_complaints.dart
  lib/screen/reports_dashboard.dart
  pubspec.lock
Labels: GSSOC'25, level 3

#459 Remove double snackbars, remove emoji keyboard overflow and add a message box to other report message issue
  android/gradle.properties
  lib/screen/discussion/discussion.dart
  lib/screen/discussion/message_reporting_screen.dart
Labels: GSSOC'25, level 3
